# Site settings
encoding: utf-8
title: Zinuo Li 
description: A portfolio about Zinuo Li 
baseurl: /personal
url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Zinuo Li 
user_description: Enjoyed title in machine learning and big data
email: zli156@hawk.iit.edu 
twitter_username: ZinuoLee
github_username:  arnoldzl
gplus_username:  zinuo.lee@gmail.com

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']