# Site settings
encoding: utf-8
title: Zinuo Li 
description: A portfolio about Zinuo Li 
baseurl:
url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Zinuo Li 
user_description: Enjoy Coding | Machine Learning | Big Data
usertitle: Software Developer
email: zli156@hawk.iit.edu 
twitter_username: ZinuoLee
facebook_username: arno.lee.56
github_username:  arnoldzl
linkedin_username: arnoldzl



# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']